### ISSUE TITLE
UCEProtect is extortionist

### ISSUE THREAD

**Issue by LogoiLab** [slunak/rbl-checker#4]
The UCEProtect RBL is a known extortion racket, its lists should not be used.

https://en.wikipedia.org/wiki/Comparison_of_DNS_blacklists#Suspect_RBL_providers

**Comment by slunak** [comment]
No problem, if you don't mind, remove them from blacklist.txt and submit a PR.

**Comment by benchonaut** [comment]
( thy, UCEprotect is more hostage-taking "non-service" than , somebody already made the person itself a website ( years ago ) .. 

https://uceprotect.wtf/ ( or even harder is what he pushes himself http://www.uceprotect.org/cart00neys/index.html ) 

operators already started dns-blocking uce-protect since they also listed https://www.linode.com/community/questions/20952/linode-blacklisted-on-uceprotect-rbl  and other "big" companies where /32 CIDR blockings would be the only "proper" way  to not drop the neighbours from the neighbours of the guy 2 blocks down the street .. 

 ( if you ever read this Mr. UCE"protect":  und die Sippenhaft wurde aus guten Gründen abgeschafft  . Lösch dich einfach ..)
